version: "3"

services:
  myDB:
    image: postgres 16
    container_name: micontenedor
    restart: always
    ports:
      - 5432:3000
    environment:
      - POSTGRES_USER=jorge
      - POSTGRES_PASSWORD=elpidio
      - POSTGRES_DB=mydb
    volumes:
      - ./postgres:/var/lib/postgresql/data
